version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-2.7
      - upload-coverage:
          requires:
            - test-3.6
            - test-3.5
            - test-2.7

default-run: &test-template
    working_directory: ~/commentcomparebot
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -e .[dev]
            pip install nose coverage
            mkdir -p ./test-results/python
            mkdir coverage-files
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests --with-coverage --cover-package=youcomment --with-xunit --xunit-file ./test-results/python/test-results.xml
            mv .coverage ./coverage-files/.coverage.$PYTHON_VERSION
      - store_test_results: &store-results
          path: test-results
      - persist_to_workspace: &persist-tests
          root: .
          paths:
            - coverage-files
jobs:
  test-3.6:
    <<: *test-template
    environment:
      PYTHON_VERSION: python36
    docker:
      - image: circleci/python:3.6

  test-3.5:
    <<: *test-template
    environment:
      PYTHON_VERSION: python35
    docker:
      - image: circleci/python:3.5

  test-2.7:
    <<: *test-template
    environment:
      PYTHON_VERSION: python27
    docker:
      - image: circleci/python:2.7

  upload-coverage: 
    docker:
      - image: circleci/python:3.6
    working_directory: ~/commentcomparebot
    steps:
      - checkout
      - attach_workspace:
          at: ~/commentcomparebot/
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Set up env
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install codacy-coverage coverage
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: Combine/upload coverage
          name:
          command: |
            cd coverage-files
            coverage combine
            coverage xml
            python-codacy-coverage -r coverage.xml