version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-2.7
      - upload-coverage

default-run: &test-template
    working_directory: ~/commentcomparebot
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -e .[dev]
            pip install nose coverage
            mkdir test-results
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests --with-coverage --cover-package=youcomment
            mkdir test-results/$PYTHON_VERSION
            coverage xml -o test-results/$PYTHON_VERSION/coverage.xml
            mv .coverage test-results/.coverage.$PYTHON_VERSION
            ls -all test-results
      - persist_to_workspace: &persist-tests
          root: .
          paths:
            - test-results
      - store_test_results: &store-results
          path: test-results/$PYTHON_VERSION
      - store_artifacts: &store-artifacts
          path: test-results/$PYTHON_VERSION
        
jobs:
  test-3.6:
    <<: *test-template
    environment:
      PYTHON_VERSION: python36
    docker:
      - image: circleci/python:3.6

  test-3.5:
    <<: *test-template
    environment:
      PYTHON_VERSION: python35
    docker:
      - image: circleci/python:3.5

  test-2.7:
    <<: *test-template
    environment:
      PYTHON_VERSION: python27
    docker:
      - image: circleci/python:2.7

  upload-coverage: 
    docker:
      - image: circleci/python:3.6
    working_directory: ~/commentcomparebot
    steps:
      - checkout
      - attach_workspace:
          at: ~/commentcomparebot/
      - run:
          name: upload coverage
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install codacy-coverage
            cd test-results
            coverage combine
            coverage xml
            python-codacy-coverage -r coverage.xml